<?php defined( 'ABSPATH' ) || exit; $about = $data['about']; ?>
<main id="contenu" class="v3-main v3-about">
  <section class="v3-editorial-hero v3-about-hero"><div><p class="v3-folio">Le Moulin · derrière la porte</p><h1>Mon<br><em>parcours.</em></h1><p><?php echo esc_html( $about['lead'] ); ?></p></div><figure><?php echo lmdl_v3_image( 'logo/embleme-transparent.png', '', '' ); ?><figcaption>Le cœur au centre des quatre ailes</figcaption></figure></section>
  <section class="v3-about-story"><p class="v3-folio">Un chemin de cœur</p><h2>Pourquoi<br><em>ce chemin ?</em></h2><div><?php foreach ( $about['story'] as $paragraph ) { echo '<p>' . esc_html( $paragraph ) . '</p>'; } ?></div><span class="v3-about-story__aside">Écoute · respect · humilité</span></section>
  <section class="v3-about-painting"><figure><?php echo lmdl_v3_image( 'art/painting-squirrel-display.webp', 'Écureuil dans l’univers Terre', '' ); ?><figcaption>Le vivant, première rencontre</figcaption></figure><div><p class="v3-folio">Ma pratique</p><h2>Une attention<br>à chacun.</h2><p><?php echo esc_html( $about['practice'] ); ?></p></div></section>
  <section class="v3-about-training"><div><p class="v3-folio">Le parcours</p><h2>De l’intuition<br>à la formation.</h2></div><p><?php echo esc_html( $about['training'] ); ?></p></section>
  <section class="v3-about-signature"><p class="v3-folio">Au cœur du lien</p><h2>Au-delà des sens.</h2><?php echo lmdl_v3_image( 'logo/signature-transparent.png', '', 'v3-about-signature__mark' ); ?><p>Je ne suis ni vétérinaire ni médecin et ne pose pas de diagnostic. Lorsqu’une situation le demande, les professionnels compétents restent essentiels.</p></section>
  <?php echo lmdl_v3_close( 'Une question ?' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped in helper. ?>
</main>
