<?php defined( 'ABSPATH' ) || exit; $service = $services['fire']; ?>
<main id="contenu" class="v3-main v3-detail v3-detail--fire">
  <section class="v3-detail-hero v3-detail-hero--fire"><div class="v3-detail-hero__copy"><a class="v3-back" href="<?php echo esc_url( home_url( '/accompagnements/' ) ); ?>">← Les quatre portes</a><p class="v3-folio">Feu · Phénix · L’énergie</p><h1>Accompagnement<br><em>énergétique</em><br>animalier.</h1><p class="v3-detail-hero__lead"><?php echo esc_html( $service['intro'] ); ?></p><a class="v3-editorial-link" href="#lire">Lire le chapitre <span aria-hidden="true">↓</span></a></div><?php echo lmdl_v3_portal_visual( 'fire', $service, true ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped in helper. ?><span class="v3-detail-hero__word" aria-hidden="true">FEU</span></section>
  <section id="lire" class="v3-fire-statement"><p class="v3-folio">Chapitre Feu · 02</p><h2>Une autre<br><em>énergie du vivant.</em></h2><div><p><?php echo esc_html( $service['lead'] ); ?></p><p><?php echo esc_html( $service['body'] ); ?></p></div></section>
  <figure class="v3-fire-art"><?php echo lmdl_v3_image( $service['painting'], 'Phénix dans l’univers Feu', '' ); ?><figcaption>Phénix · Feu</figcaption></figure>
  <section class="v3-fire-note"><p class="v3-folio">La posture</p><h2>L’attention avant l’effet.</h2><p><?php echo esc_html( $service['note'] ); ?></p></section>
  <section class="v3-detail-practical"><p class="v3-folio">En pratique</p><h2>Un cadre responsable.</h2><p><?php echo esc_html( $service['practical'] ); ?></p><p>Je ne pose pas de diagnostic médical ou vétérinaire. Les professionnels compétents restent essentiels lorsque la situation le demande.</p></section>
  <?php echo lmdl_v3_related( 'fire' ); echo lmdl_v3_close( 'Poursuivre le chemin ?' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped in helpers. ?>
</main>
